version: 2
jobs:
  build: 
    docker:
      -image: circleci/python:3.6.1
    
    steps:
      - checkout
      
      - run:
        name: install packages
        command: |
          make install
      - run:
        name: run lint
        command: |
          make lint
            
